### ISSUE TITLE
Extract Blood-type Validation From Donor Matching Function

### ISSUE THREAD

**Issue by Akamaozu** [hemanth/blood-donor#1]
It might be better if the blood-type validation is extracted from this module into its own module that this depends on. 

Sometimes you just want to know if the user has submitted a valid blood-type and this will do way more work after confirming the input type is valid.

**Comment by Akamaozu** [comment]
Just in case, ended up writing a small lib just for validation. 

Supports simple or strict validation, sync or async usage (_async has detailed errors_) and has tests.

https://github.com/Akamaozu/bloodtype-validator

**Comment by hemanth** [comment]
Nice, PRs welcomed :)
